name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm ci --force
      - run: npx playwright install
      - name: Run build
        run: 'npm run build'
      - name: Run e2e
        run: 'npm run e2e'
